---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task
inputs:
- name: ci-images-git-repo
outputs:
- name: image
caches:
- path: ci-image-cache
params:
  CONTEXT: ci-images-git-repo/ci/images
  DOCKERFILE: ci-images-git-repo/ci/images/((ci-image-name))/Dockerfile
  DOCKER_HUB_USERNAME: ((docker-hub-username))
  DOCKER_HUB_PASSWORD: ((docker-hub-password))
run:
  path: /bin/sh
  args:
  - "-c"
  - |
    mkdir -p /root/.docker
    AUTH="$(echo -n "${DOCKER_HUB_USERNAME}:${DOCKER_HUB_PASSWORD}" | base64 -w 0)"
    cat > docker-creds/config.json <<EOF
    "auths": { "${DOCKER_REGISTRY}": { "auth": "$AUTH" }}}
    EOF
    build